### ISSUE TITLE
build (12.x) fs.rmSync is not a function

### ISSUE THREAD

**Issue by jeffperezfrade** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-jeffperezfrade#1]
@esegredo Hola profe, en la action de Tests me pasan las builds (14.x) y (16.x) pero la (12.x) me sale el error  'fs.rmSync is not a function'. No se si habría otra manera de hacerlo, saludos.

**Comment by jeffperezfrade** [comment]
Sería de muy mala práctica quitar que haga test en 12.x?

**Comment by esegredo** [comment]
Hola Jeff,

El asunto es que en la versión 12 de Node la función rmSync no se encontraba disponible en el API de acceso al sistema de ficheros. Es por ello que obtienes ese error. Teniendo en cuenta esto, tu código (y cualquiera que use dicha función) no sería compatible con versiones de Node iguales o inferiores a la 12.

No es una mala práctica quitar la versión 12. De hecho, si quieres que las pruebas pasen, deberás quitarla de tu flujo de GitHub.

Saludos.
